services:
  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.tmp/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  ingest-data-redis:
    depends_on:
      redis:
        condition: service_healthy
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env 
    command: >
      uv run src/redis/ingest_data.py

  ingest-data-azureai:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env 
    command: >
      uv run src/azureai/ingest_data.py

  remove-data-redis:
    depends_on:
      redis:
        condition: service_healthy
    build: .
    env_file:
      - .env 
    command: >
      uv run src/redis/remove_data.py

  remove-data-azureai:
    build: .
    env_file:
      - .env 
    command: >
      uv run src/azureai/remove_data.py

  query-redis:
    depends_on:
      redis:
        condition: service_healthy
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: >
      uv run src/redis/main.py "$QUERY_STRING"

  query-azureai:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: >
      uv run src/azureai/main.py "$QUERY_STRING"